name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
      - name: verify `lake exe` works
        run: |
          lake exe hilbertcurveblogpost
          test -f _site/index.html
      - name: Setup Pages
        if: github.event_name == 'workflow_dispatch'
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        if: github.event_name == 'workflow_dispatch'
        id: deployment
        uses: actions/deploy-pages@v4
